org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.21.1,1.21.3)

neo_version=21.1.200
neo_version_range=[21.1.181,)
loader_version_range=[4,)

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

mod_id=shortstacks
mod_name=Short Stacks
mod_license=GNU GPL 3.0
mod_version=1.2.1
mod_group_id=com.momosoftworks
mod_authors=
mod_description=
